resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxRetryAttempts : 3
        waitDuration: 5s
  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitForPeriod: 1
        limitRefreshPeriod: 5s
        timeoutDuration: 1s
  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 1000
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true